//this is data that is generated by AI which is stored in database for use of listings
//this data is stored by index.js

const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Relax in a peaceful beachfront cottage with ocean views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 1500,
    location: "Goa",
    country: "India",
  },
  {
    title: "Modern City Apartment",
    description: "A stylish apartment located in the heart of the city.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    },
    price: 1200,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Mountain View Cabin",
    description: "Cabin with breathtaking mountain views and fresh air.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
    },
    price: 1400,
    location: "Manali",
    country: "India",
  },
  {
    title: "Luxury Villa with Pool",
    description: "Private luxury villa with swimming pool and garden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    },
    price: 3500,
    location: "Lonavala",
    country: "India",
  },
  {
    title: "Compact Studio Apartment",
    description: "A compact and modern studio ideal for solo stays.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1524758631624-e2822e304c36",
    },
    price: 850,
    location: "Pune",
    country: "India",
  },
  {
    title: "Nature View Wooden Cottage",
    description: "Wooden cottage surrounded by greenery and fresh air.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e",
    },
    price: 1200,
    location: "Wayanad",
    country: "India",
  },
  {
    title: "Lake View Cottage",
    description: "Quiet cottage overlooking a calm lake.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c",
    },
    price: 1300,
    location: "Nainital",
    country: "India",
  },
  {
    title: "Heritage Haveli Stay",
    description: "Traditional haveli experience with royal interiors.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
    },
    price: 2000,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Riverside Wooden Hut",
    description: "Wooden hut beside a flowing river.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 1000,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Snow View Chalet",
    description: "Warm chalet with snowy mountain views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66",
    },
    price: 2500,
    location: "Gulmarg",
    country: "India",
  },

  // --- remaining 20 ---
  {
    title: "Beach Hut Stay",
    description: "Simple hut just steps away from the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    },
    price: 900,
    location: "Gokarna",
    country: "India",
  },
  {
    title: "Urban Budget Room",
    description: "Affordable room in a prime city location.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    },
    price: 700,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Luxury Penthouse",
    description: "Top-floor penthouse with skyline views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
    },
    price: 4000,
    location: "Bengaluru",
    country: "India",
  },
  {
    title: "Hilltop Resort Room",
    description: "Stay on a hilltop with stunning sunrise views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    },
    price: 2200,
    location: "Ooty",
    country: "India",
  },
  {
    title: "Eco Bamboo Cottage",
    description: "Eco-friendly bamboo stay surrounded by greenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1544986581-efac024faf62",
    },
    price: 1100,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Royal Palace Room",
    description: "Live like royalty inside a palace stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    },
    price: 4500,
    location: "Jodhpur",
    country: "India",
  },
  {
    title: "Island Beach Villa",
    description: "Private beach villa on a peaceful island.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21",
    },
    price: 5200,
    location: "Andaman",
    country: "India",
  },
  {
    title: "Desert Stone Villa",
    description: "Stone-built villa in the desert landscape.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090",
    },
    price: 1600,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "City View Apartment",
    description: "Apartment with clear city skyline view.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    },
    price: 1400,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Cliffside Ocean Villa",
    description: "Luxury villa built on an ocean-facing cliff.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    },
    price: 3800,
    location: "Varkala",
    country: "India",
  },
];

module.exports = { data: sampleListings };
